# Generated by Django 5.0.1 on 2024-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
